# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.CharField(blank=True, max_length=100, null=True, verbose_name='estadio')),
                ('stage', models.CharField(max_length=100, verbose_name='etapa del torneo')),
                ('date', models.DateTimeField(verbose_name='fecha del partido')),
                ('is_draw', models.BooleanField(default=False, verbose_name='empate')),
                ('result', models.CharField(blank=True, max_length=10, null=True, verbose_name='resultado del partido')),
                ('is_finished', models.BooleanField(default=False, verbose_name='partido finalizado')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='countries.country')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='countries.country')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='countries.country')),
            ],
            options={
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
                'ordering': ['date'],
            },
        ),
    ]
