# Generated by Django 5.2.15 on 2026-06-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_draw',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='goals_team_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='goles del equipo 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_team_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='goles del equipo 2'),
        ),
    ]
