# Generated by Django 5.2.15 on 2026-06-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_is_draw_remove_match_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalties_team_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='penales del equipo 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_team_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='penales del equipo 2'),
        ),
    ]
